### ISSUE TITLE
Creation of an annoying .user-config.json file everywhere 

### ISSUE THREAD

**Issue by pmaoui** [mjurczyk/json-viewer#15]
Hello,
Each time I use json-viewer, it creates an hidden file called `.user-config.json`.
It can be annoying if the file is created in a versionned folder.

It is done here:
https://github.com/mjurczyk/json-viewer/blob/cfb3605b37bfe836bcdca5efee689f9028e5d084/src/utils/config/index.js#L7

**Comment by mjurczyk** [comment]
Fixed! Should now be created only once in the `json-viewer` directory (either npm global directory or `node_modules/json-viewer`). Thanks for pointing it out, @poupougnac !
