### ISSUE TITLE
json-viewer arrow images not loading sometimes

### ISSUE THREAD

**Issue by sagar-wadke2302** [mjurczyk/json-viewer#18]
Hi,

json-viewer arrows are not loading few times, the error shows in the console for violation of "Content Security Policy". After applying the suggested fixes on google code. Below image is not loading.
File Name: "jsoneditor-icons.svg"

Kindly help! Thanks in advance!

![console-error](https://user-images.githubusercontent.com/59645128/133721178-2cca4300-5e05-4541-b894-e9d834e9a652.png)
![error](https://user-images.githubusercontent.com/59645128/133721180-61bb0422-aaec-45d8-bd2a-8d3597930803.png)

**Comment by mjurczyk** [comment]
Hm - are you sure this is the correct repository though? `json-viewer` is a script for terminal, and it doesn't really use SVG icons.
