### ISSUE TITLE
Don't force .json extension

### ISSUE THREAD

**Issue by ccoenen** [mjurczyk/json-viewer#2]
The tool currently enforces `json` file extension, probably as a convenience feature. It does so right here: https://github.com/mjurczyk/json-viewer/blob/d3e00b35063a3b1075b526c4ee9e3ca2781d7c9d/src/json-viewer.js#L139

This way, it's not possible to view files that don't end with `.json`

One can't work around this with stdinput (meaning: i can't pipe content to json like this: `cat some/odd/filename | json -c -`)

**Comment by obstschale** [comment]
I was looking for a tool, which can pretty print JSON in my terminal, but I want to use other tools generating the JSON string and pipe it to `json`. However, like @ccoenen says, piping is not possible with `json-viewer` :/

**Comment by mjurczyk** [comment]
@ccoenen @obstschale
Hey, thank you for the idea - pipe and non-json files functionality will be merged into `master` this Friday along with version `json-viewer@2.0` (details added in https://github.com/mjurczyk/json-viewer/commit/1bd7cd47a45490314693e58ebda516864193158c)

**Comment by ccoenen** [comment]
This is going to be awesome! Now we can `curl some.domain/some/api/stuff.json | json -c -` :D

**Comment by mjurczyk** [comment]
Solved during the refactor in [v2.0](https://www.npmjs.com/package/json-viewer), closing the issue 🙂
